package com.isi.hris.persistence.master.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * MasterClientEmailSettingId generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class MasterClientEmailSettingId implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Column(name = "ClientID", nullable = false)
	private int clientId;

	@Column(name = "SupportEmailAddress", length = 120)
	private String supportEmailAddress;

	@Column(name = "SMTPHost", length = 10)
	private String smtphost;

	@Column(name = "SMTPPort")
	private Integer smtpport;

	@Column(name = "SMTPUserName", length = 120)
	private String smtpuserName;

	@Column(name = "SMTPPassword", length = 120)
	private String smtppassword;

	@Column(name = "SMTPStartTLS", nullable = false)
	private byte smtpstartTls;

	@Column(name = "SMTPAuth", nullable = false)
	private byte smtpauth;

	@Column(name = "SMTPTLS", nullable = false)
	private byte smtptls;

	@Column(name = "SMTPDebug", nullable = false)
	private byte smtpdebug;
}
